### ISSUE TITLE
Implement the `PM` family of API commands

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#101]
The `PM` API command is used to manipulated planned maintenance entries in Zino (as implemented in #194)

However, the `PM` command feature multiple subcommands, which will necessitate changes to how the `Zino1BaseServerProtocol` dispatches commands to methods.  Example from Zino 1 server session:

```
PM HELP
200- PM subcommands are:
200  ADD LIST CANCEL DETAILS MATCHING ADDLOG LOG
```

### Subtasks

- [x] #255
- [x] Implement the `PM ADD` API subcommand
- [x] Implement the `PM LIST` API subcommand
- [x] Implement the `PM CANCEL` API subcommand
- [x] Implement the `PM DETAILS` API subcommand
- [x] Implement the `PM MATCHING` API subcommand
- [x] Implement the `PM ADDLOG` API subcommand
- [x] Implement the `PM LOG` API subcommand
