### ISSUE TITLE
Implement SNMP trap reception mechanism

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/zino#173]
### Design considerations

Zino 1 uses a trap daemon model taken from Scotty, wherein an SNMP trap multiplexer daemon (`straps` or `nmtrapd`) is run as root, and any Scotty program (like Zino) that wants a copy of all received traps can run as unprivileged users and connect to a UNIX socket to receive a  stream of the received trap messages.

While this is a really nice model for both debugging and for having multiple small and independent programs that can run on the same machine and react to traps, we don't see this as an essential model to replicate.

In Zino 2, we will instead opt for a model where the Zino program itself will listen for incoming SNMP trap messages (on UDP port 162).  This does have the side-effect that the Zino program must be started by root, and needs to be able to switch to a less privileged user immediately after opening the privileged port 162.

A model where Zino connects to a trap message multiplexer can be added later if deemed necessary.

### Sub-tasks

- [x] #189 
- [x] #193
- [x] Traps that are handled by the original Zino in some way or the other

  - These traps cause Zino to take action:
    - [x] #232
    - [x] #292
    - [x] #288

  - These traps are only parsed and logged (in simple or less simple ways):
    - [x] #226
    - [x] #319

  - These traps seem to be just ignored entirely:
    - [x] `bgpBackwardTransition` (a.k.a. `BGP4-MIB::bgpBackwardTransition`)
    - [x] `BGP4-MIB::bgpBackwardTransNotification`
    - [x] `jnxBgpM2Experiment.1.1.0.2` (a.k.a `BGP4-V2-MIB-JUNIPER::jnxBgpM2BackwardTransition`)
    - [x] `SNMPv2-MIB::authenticationFailure`
    - [x] `CISCOTRAP-MIB::tcpConnectionClose` (but contains some commented out logging code)
    - [x] `BGP4-V2-MIB-JUNIPER::jnxBgpM2BackwardTransition`

  - The default trap handler just logs incoming trap details as an "unknown trap"

**Comment by lunkwill42** [comment]
The `straps` SNMP trap multiplexer is described here: https://linuxcertif.com/man/8/straps/  - but I am hard pressed to find the actual package or source code, at the moment...

**Comment by lunkwill42** [comment]
Some more digging, and it turns out `straps` was renamed to `nmtrapd` in 1996 (!).  Source code seems to be available here: https://github.com/flightaware/scotty/blob/23645564467704119dca051b6c8b16a4c56b74af/tnm/unix/nmtrapd.c

**Comment by lunkwill42** [comment]
A PySNMP reference: https://pysnmp.readthedocs.io/en/latest/examples/v3arch/asyncore/manager/ntfrcv/transport-tweaks.html

**Comment by he32** [comment]
> ### Design considerations
> 
> Zino 1 uses a trap daemon model taken from Scotty, wherein an SNMP trap multiplexer daemon (`straps` or `nmtrapd`) is run as root, and any Scotty program (like Zino) that wants a copy of all received traps can run as unprivileged users and connect to a UNIX socket to receive a stream of the received trap messages.
> 
> While this is a really nice model for both debugging and for having multiple small and independent programs that can run on the same machine and react to traps, we don't see this as an essential model to replicate.
> 
> In Zino 2, we will instead opt for a model where the Zino program itself will listen for incoming SNMP trap messages (on UDP port 162). This does have the side-effect that the Zino program must be started by root, and needs to be able to switch to a less privileged user immediately after opening the privileged port 162.
> 
> A model where Zino connects to a trap message multiplexer can be added later if deemed necessary.

Please note that we're already using this multiplexing method actively.
We have a separate SNMP trap listening program running on our main
status monitoring host which takes note of configuration change trap
messages, and appropriately delayed posts messages using curl to our
oxidized instance to pick up the newly modified configuration in a somewhat
timely manner.

The above method means that you can only have a single program listening
for SNMP trap messages on this host, and you need to "burn a new IP address"
for another host and configure all your routers to also send trap messages that
direction if you want to consume SNMP trap messages for more than one single
purpose.  I know also that in the past there has been bugs in our preferred router
OS when more than N (where N was 2?) trap recipients were configured.

**Comment by lunkwill42** [comment]
All associated sub-tasks have been closed, this can now also be closed
